function [A_pos,A_pos_0,A_pos_1,A_neg,A_neg_0,A_neg_1,D_nonlin,...
    D_nonlin_bd,D_lin,D_lin_bd] = aMatrixConstruction(xn,dx)

    %A matrices now must be space-dependent -- for advection
    A_pos = @(se,sw,ve,vw,ind,dn) sparse([ind ind ind],[ind-dn ind ind+dn],...
        [vw.*(-1+sw/2); (ve.*(1-1*se/2)-vw.*sw/2); (ve.*se/2)],2*xn,2*xn);
    
    A_pos_0 = @(se,ve,ind,dn) sparse([ind ind],[ind ind+dn],...
        [ve.*(1-1*se/2); ve.*se/2],2*xn,2*xn);

    A_pos_1 = @(sw,vw,ind,dn) sparse([ind ind],[ind-dn ind],[vw.*(-1+sw/2); ...
        (-vw.*sw/2)],2*xn,2*xn);
    
    %matrix for nonlinear diffusion


    A_neg = @(se,sw,ve,vw,ind,dn) sparse([ind ind ind],[ind-dn ind ind+dn],...
        [(-vw.*sw/2); (ve.*se/2+vw.*sw/2-vw); (ve-ve.*se/2)],2*xn,2*xn);

    A_neg_1 = @(sw,vw,ind,dn) sparse([ind ind],[ind-dn ind],[(-vw.*sw/2); ...
        (vw.*sw/2-vw)],2*xn,2*xn);

    A_neg_0 = @(se,ve,ind,dn) sparse([ind ind],[ind ind+dn],...
        [ve.*se/2; (ve-ve.*se/2)],2*xn,2*xn);


    D = @(u,ind) u(ind).^2; 
    
    D_nonlin = @(u,ind) sparse([ind ind ind],...
      [ind ind-1 ind+1],...
      [-(D(u,ind+1) +2*D(u,ind) + ...
      D(u,ind-1)) (D(u,ind) + ...
      D(u,ind-1)) (D(u,ind+1) + ...
      D(u,ind))],2*xn,2*xn)/(2*dx)^2;

  
%     
%     D_nonlin_bd = @(u,ind0,ind1) sparse([ind0 ind0 ind1 ind1],[ind0 (ind0+1) ...
%         ind1 ind1-1],[-(2*D(u,ind0) + ...
%         2*D(u,ind0+1)) (2*D(u,ind0) + ...
%         2*D(u,ind0+1)) -(2*D(u,ind1) +...
%         2*D(u,ind1-1)) (2*D(u,ind1) +...
%         2*D(u,ind1-1))],2*xn,2*xn)/(2*dx)^2;
%

    
    D_nonlin_bd = @(u,ind1) sparse([ind1 ind1],[ind1 ind1-1],...
        [-(2*D(u,ind1) +...
        2*D(u,ind1-1)) (2*D(u,ind1) +...
        2*D(u,ind1-1))],2*xn,2*xn)/(2*dx)^2;
    


    D_lin = @(ind) sparse([ind ind ind],[ind-1 ind ind+1],[ones(size(ind))...
        -2*ones(size(ind)) ones(size(ind))],2*xn,2*xn)/(2*dx)^2;
    
    
    D_lin_bd = @(ind0,ind1) sparse([ind0 ind0 ind1 ind1],[ind0 ind0+1 ind1 ...
        ind1-1],[-2*ones(size(ind0)) 2*ones(size(ind0)) -2*ones(size(ind1))...
        2*ones(size(ind1))],2*xn,2*xn)/(2*dx)^2;
end